// project_soc.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module project_soc (
		input  wire        audio_i2c_0_i2c_serial_sda_in,                 //                 audio_i2c_0_i2c_serial.sda_in
		input  wire        audio_i2c_0_i2c_serial_scl_in,                 //                                       .scl_in
		output wire        audio_i2c_0_i2c_serial_sda_oe,                 //                                       .sda_oe
		output wire        audio_i2c_0_i2c_serial_scl_oe,                 //                                       .scl_oe
		output wire [1:0]  cam_ctrl_export,                               //                               cam_ctrl.export
		input  wire        clk_clk,                                       //                                    clk.clk
		output wire [31:0] effect_event_pio_external_connection_export,   //   effect_event_pio_external_connection.export
		input  wire [31:0] frame_counter_pio_external_connection_export,  //  frame_counter_pio_external_connection.export
		output wire [31:0] fruit0_desc_pio_external_connection_export,    //    fruit0_desc_pio_external_connection.export
		output wire [31:0] fruit1_desc_pio_external_connection_export,    //    fruit1_desc_pio_external_connection.export
		output wire [31:0] fruit2_desc_pio_external_connection_export,    //    fruit2_desc_pio_external_connection.export
		output wire [31:0] fruit3_desc_pio_external_connection_export,    //    fruit3_desc_pio_external_connection.export
		output wire [31:0] game_ctrl_pio_external_connection_export,      //      game_ctrl_pio_external_connection.export
		input  wire        i2c_0_i2c_serial_sda_in,                       //                       i2c_0_i2c_serial.sda_in
		input  wire        i2c_0_i2c_serial_scl_in,                       //                                       .scl_in
		output wire        i2c_0_i2c_serial_sda_oe,                       //                                       .sda_oe
		output wire        i2c_0_i2c_serial_scl_oe,                       //                                       .scl_oe
		input  wire [3:0]  keys_export,                                   //                                   keys.export
		input  wire        reset_reset_n,                                 //                                  reset.reset_n
		output wire        sdram_clk_clk,                                 //                              sdram_clk.clk
		output wire [12:0] sdram_wire_addr,                               //                             sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,                                 //                                       .ba
		output wire        sdram_wire_cas_n,                              //                                       .cas_n
		output wire        sdram_wire_cke,                                //                                       .cke
		output wire        sdram_wire_cs_n,                               //                                       .cs_n
		inout  wire [31:0] sdram_wire_dq,                                 //                                       .dq
		output wire [3:0]  sdram_wire_dqm,                                //                                       .dqm
		output wire        sdram_wire_ras_n,                              //                                       .ras_n
		output wire        sdram_wire_we_n,                               //                                       .we_n
		input  wire [31:0] tracker_status_pio_external_connection_export  // tracker_status_pio_external_connection.export
	);

	wire         sdram_pll_c0_clk;                                            // sdram_pll:c0 -> [mm_interconnect_0:sdram_pll_c0_clk, rst_controller_002:clk, sdram:clk]
	wire  [31:0] nios2_gen2_0_data_master_readdata;                           // mm_interconnect_0:nios2_gen2_0_data_master_readdata -> nios2_gen2_0:d_readdata
	wire         nios2_gen2_0_data_master_waitrequest;                        // mm_interconnect_0:nios2_gen2_0_data_master_waitrequest -> nios2_gen2_0:d_waitrequest
	wire         nios2_gen2_0_data_master_debugaccess;                        // nios2_gen2_0:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_gen2_0_data_master_debugaccess
	wire  [28:0] nios2_gen2_0_data_master_address;                            // nios2_gen2_0:d_address -> mm_interconnect_0:nios2_gen2_0_data_master_address
	wire   [3:0] nios2_gen2_0_data_master_byteenable;                         // nios2_gen2_0:d_byteenable -> mm_interconnect_0:nios2_gen2_0_data_master_byteenable
	wire         nios2_gen2_0_data_master_read;                               // nios2_gen2_0:d_read -> mm_interconnect_0:nios2_gen2_0_data_master_read
	wire         nios2_gen2_0_data_master_write;                              // nios2_gen2_0:d_write -> mm_interconnect_0:nios2_gen2_0_data_master_write
	wire  [31:0] nios2_gen2_0_data_master_writedata;                          // nios2_gen2_0:d_writedata -> mm_interconnect_0:nios2_gen2_0_data_master_writedata
	wire  [31:0] nios2_gen2_0_instruction_master_readdata;                    // mm_interconnect_0:nios2_gen2_0_instruction_master_readdata -> nios2_gen2_0:i_readdata
	wire         nios2_gen2_0_instruction_master_waitrequest;                 // mm_interconnect_0:nios2_gen2_0_instruction_master_waitrequest -> nios2_gen2_0:i_waitrequest
	wire  [28:0] nios2_gen2_0_instruction_master_address;                     // nios2_gen2_0:i_address -> mm_interconnect_0:nios2_gen2_0_instruction_master_address
	wire         nios2_gen2_0_instruction_master_read;                        // nios2_gen2_0:i_read -> mm_interconnect_0:nios2_gen2_0_instruction_master_read
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;    // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest; // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata;       // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;        // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_i2c_0_csr_readdata;                        // i2c_0:readdata -> mm_interconnect_0:i2c_0_csr_readdata
	wire   [3:0] mm_interconnect_0_i2c_0_csr_address;                         // mm_interconnect_0:i2c_0_csr_address -> i2c_0:addr
	wire         mm_interconnect_0_i2c_0_csr_read;                            // mm_interconnect_0:i2c_0_csr_read -> i2c_0:read
	wire         mm_interconnect_0_i2c_0_csr_write;                           // mm_interconnect_0:i2c_0_csr_write -> i2c_0:write
	wire  [31:0] mm_interconnect_0_i2c_0_csr_writedata;                       // mm_interconnect_0:i2c_0_csr_writedata -> i2c_0:writedata
	wire  [31:0] mm_interconnect_0_audio_i2c_0_csr_readdata;                  // audio_i2c_0:readdata -> mm_interconnect_0:audio_i2c_0_csr_readdata
	wire   [3:0] mm_interconnect_0_audio_i2c_0_csr_address;                   // mm_interconnect_0:audio_i2c_0_csr_address -> audio_i2c_0:addr
	wire         mm_interconnect_0_audio_i2c_0_csr_read;                      // mm_interconnect_0:audio_i2c_0_csr_read -> audio_i2c_0:read
	wire         mm_interconnect_0_audio_i2c_0_csr_write;                     // mm_interconnect_0:audio_i2c_0_csr_write -> audio_i2c_0:write
	wire  [31:0] mm_interconnect_0_audio_i2c_0_csr_writedata;                 // mm_interconnect_0:audio_i2c_0_csr_writedata -> audio_i2c_0:writedata
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata;     // nios2_gen2_0:debug_mem_slave_readdata -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest;  // nios2_gen2_0:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess;  // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_debugaccess -> nios2_gen2_0:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address;      // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_address -> nios2_gen2_0:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read;         // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_read -> nios2_gen2_0:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable;   // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_byteenable -> nios2_gen2_0:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write;        // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_write -> nios2_gen2_0:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata;    // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_writedata -> nios2_gen2_0:debug_mem_slave_writedata
	wire  [31:0] mm_interconnect_0_sdram_pll_pll_slave_readdata;              // sdram_pll:readdata -> mm_interconnect_0:sdram_pll_pll_slave_readdata
	wire   [1:0] mm_interconnect_0_sdram_pll_pll_slave_address;               // mm_interconnect_0:sdram_pll_pll_slave_address -> sdram_pll:address
	wire         mm_interconnect_0_sdram_pll_pll_slave_read;                  // mm_interconnect_0:sdram_pll_pll_slave_read -> sdram_pll:read
	wire         mm_interconnect_0_sdram_pll_pll_slave_write;                 // mm_interconnect_0:sdram_pll_pll_slave_write -> sdram_pll:write
	wire  [31:0] mm_interconnect_0_sdram_pll_pll_slave_writedata;             // mm_interconnect_0:sdram_pll_pll_slave_writedata -> sdram_pll:writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_chipselect;            // mm_interconnect_0:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;              // onchip_memory2_0:readdata -> mm_interconnect_0:onchip_memory2_0_s1_readdata
	wire   [1:0] mm_interconnect_0_onchip_memory2_0_s1_address;               // mm_interconnect_0:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire   [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;            // mm_interconnect_0:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire         mm_interconnect_0_onchip_memory2_0_s1_write;                 // mm_interconnect_0:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;             // mm_interconnect_0:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_clken;                 // mm_interconnect_0:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire         mm_interconnect_0_sdram_s1_chipselect;                       // mm_interconnect_0:sdram_s1_chipselect -> sdram:az_cs
	wire  [31:0] mm_interconnect_0_sdram_s1_readdata;                         // sdram:za_data -> mm_interconnect_0:sdram_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                      // sdram:za_waitrequest -> mm_interconnect_0:sdram_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                          // mm_interconnect_0:sdram_s1_address -> sdram:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                             // mm_interconnect_0:sdram_s1_read -> sdram:az_rd_n
	wire   [3:0] mm_interconnect_0_sdram_s1_byteenable;                       // mm_interconnect_0:sdram_s1_byteenable -> sdram:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                    // sdram:za_valid -> mm_interconnect_0:sdram_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                            // mm_interconnect_0:sdram_s1_write -> sdram:az_wr_n
	wire  [31:0] mm_interconnect_0_sdram_s1_writedata;                        // mm_interconnect_0:sdram_s1_writedata -> sdram:az_data
	wire         mm_interconnect_0_cam_ctrl_pio_s1_chipselect;                // mm_interconnect_0:cam_ctrl_pio_s1_chipselect -> cam_ctrl_pio:chipselect
	wire  [31:0] mm_interconnect_0_cam_ctrl_pio_s1_readdata;                  // cam_ctrl_pio:readdata -> mm_interconnect_0:cam_ctrl_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_cam_ctrl_pio_s1_address;                   // mm_interconnect_0:cam_ctrl_pio_s1_address -> cam_ctrl_pio:address
	wire         mm_interconnect_0_cam_ctrl_pio_s1_write;                     // mm_interconnect_0:cam_ctrl_pio_s1_write -> cam_ctrl_pio:write_n
	wire  [31:0] mm_interconnect_0_cam_ctrl_pio_s1_writedata;                 // mm_interconnect_0:cam_ctrl_pio_s1_writedata -> cam_ctrl_pio:writedata
	wire  [31:0] mm_interconnect_0_keys_pio_s1_readdata;                      // keys_pio:readdata -> mm_interconnect_0:keys_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_keys_pio_s1_address;                       // mm_interconnect_0:keys_pio_s1_address -> keys_pio:address
	wire  [31:0] mm_interconnect_0_frame_counter_pio_s1_readdata;             // frame_counter_pio:readdata -> mm_interconnect_0:frame_counter_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_frame_counter_pio_s1_address;              // mm_interconnect_0:frame_counter_pio_s1_address -> frame_counter_pio:address
	wire  [31:0] mm_interconnect_0_tracker_status_pio_s1_readdata;            // tracker_status_pio:readdata -> mm_interconnect_0:tracker_status_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_tracker_status_pio_s1_address;             // mm_interconnect_0:tracker_status_pio_s1_address -> tracker_status_pio:address
	wire         mm_interconnect_0_game_ctrl_pio_s1_chipselect;               // mm_interconnect_0:game_ctrl_pio_s1_chipselect -> game_ctrl_pio:chipselect
	wire  [31:0] mm_interconnect_0_game_ctrl_pio_s1_readdata;                 // game_ctrl_pio:readdata -> mm_interconnect_0:game_ctrl_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_game_ctrl_pio_s1_address;                  // mm_interconnect_0:game_ctrl_pio_s1_address -> game_ctrl_pio:address
	wire         mm_interconnect_0_game_ctrl_pio_s1_write;                    // mm_interconnect_0:game_ctrl_pio_s1_write -> game_ctrl_pio:write_n
	wire  [31:0] mm_interconnect_0_game_ctrl_pio_s1_writedata;                // mm_interconnect_0:game_ctrl_pio_s1_writedata -> game_ctrl_pio:writedata
	wire         mm_interconnect_0_fruit0_desc_pio_s1_chipselect;             // mm_interconnect_0:fruit0_desc_pio_s1_chipselect -> fruit0_desc_pio:chipselect
	wire  [31:0] mm_interconnect_0_fruit0_desc_pio_s1_readdata;               // fruit0_desc_pio:readdata -> mm_interconnect_0:fruit0_desc_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_fruit0_desc_pio_s1_address;                // mm_interconnect_0:fruit0_desc_pio_s1_address -> fruit0_desc_pio:address
	wire         mm_interconnect_0_fruit0_desc_pio_s1_write;                  // mm_interconnect_0:fruit0_desc_pio_s1_write -> fruit0_desc_pio:write_n
	wire  [31:0] mm_interconnect_0_fruit0_desc_pio_s1_writedata;              // mm_interconnect_0:fruit0_desc_pio_s1_writedata -> fruit0_desc_pio:writedata
	wire         mm_interconnect_0_fruit1_desc_pio_s1_chipselect;             // mm_interconnect_0:fruit1_desc_pio_s1_chipselect -> fruit1_desc_pio:chipselect
	wire  [31:0] mm_interconnect_0_fruit1_desc_pio_s1_readdata;               // fruit1_desc_pio:readdata -> mm_interconnect_0:fruit1_desc_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_fruit1_desc_pio_s1_address;                // mm_interconnect_0:fruit1_desc_pio_s1_address -> fruit1_desc_pio:address
	wire         mm_interconnect_0_fruit1_desc_pio_s1_write;                  // mm_interconnect_0:fruit1_desc_pio_s1_write -> fruit1_desc_pio:write_n
	wire  [31:0] mm_interconnect_0_fruit1_desc_pio_s1_writedata;              // mm_interconnect_0:fruit1_desc_pio_s1_writedata -> fruit1_desc_pio:writedata
	wire         mm_interconnect_0_fruit2_desc_pio_s1_chipselect;             // mm_interconnect_0:fruit2_desc_pio_s1_chipselect -> fruit2_desc_pio:chipselect
	wire  [31:0] mm_interconnect_0_fruit2_desc_pio_s1_readdata;               // fruit2_desc_pio:readdata -> mm_interconnect_0:fruit2_desc_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_fruit2_desc_pio_s1_address;                // mm_interconnect_0:fruit2_desc_pio_s1_address -> fruit2_desc_pio:address
	wire         mm_interconnect_0_fruit2_desc_pio_s1_write;                  // mm_interconnect_0:fruit2_desc_pio_s1_write -> fruit2_desc_pio:write_n
	wire  [31:0] mm_interconnect_0_fruit2_desc_pio_s1_writedata;              // mm_interconnect_0:fruit2_desc_pio_s1_writedata -> fruit2_desc_pio:writedata
	wire         mm_interconnect_0_fruit3_desc_pio_s1_chipselect;             // mm_interconnect_0:fruit3_desc_pio_s1_chipselect -> fruit3_desc_pio:chipselect
	wire  [31:0] mm_interconnect_0_fruit3_desc_pio_s1_readdata;               // fruit3_desc_pio:readdata -> mm_interconnect_0:fruit3_desc_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_fruit3_desc_pio_s1_address;                // mm_interconnect_0:fruit3_desc_pio_s1_address -> fruit3_desc_pio:address
	wire         mm_interconnect_0_fruit3_desc_pio_s1_write;                  // mm_interconnect_0:fruit3_desc_pio_s1_write -> fruit3_desc_pio:write_n
	wire  [31:0] mm_interconnect_0_fruit3_desc_pio_s1_writedata;              // mm_interconnect_0:fruit3_desc_pio_s1_writedata -> fruit3_desc_pio:writedata
	wire         mm_interconnect_0_effect_event_pio_s1_chipselect;            // mm_interconnect_0:effect_event_pio_s1_chipselect -> effect_event_pio:chipselect
	wire  [31:0] mm_interconnect_0_effect_event_pio_s1_readdata;              // effect_event_pio:readdata -> mm_interconnect_0:effect_event_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_effect_event_pio_s1_address;               // mm_interconnect_0:effect_event_pio_s1_address -> effect_event_pio:address
	wire         mm_interconnect_0_effect_event_pio_s1_write;                 // mm_interconnect_0:effect_event_pio_s1_write -> effect_event_pio:write_n
	wire  [31:0] mm_interconnect_0_effect_event_pio_s1_writedata;             // mm_interconnect_0:effect_event_pio_s1_writedata -> effect_event_pio:writedata
	wire         irq_mapper_receiver0_irq;                                    // jtag_uart_0:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_gen2_0_irq_irq;                                        // irq_mapper:sender_irq -> nios2_gen2_0:irq
	wire         rst_controller_reset_out_reset;                              // rst_controller:reset_out -> [audio_i2c_0:rst_n, cam_ctrl_pio:reset_n, effect_event_pio:reset_n, frame_counter_pio:reset_n, fruit0_desc_pio:reset_n, fruit1_desc_pio:reset_n, fruit2_desc_pio:reset_n, fruit3_desc_pio:reset_n, game_ctrl_pio:reset_n, i2c_0:rst_n, irq_mapper:reset, keys_pio:reset_n, mm_interconnect_0:nios2_gen2_0_reset_reset_bridge_in_reset_reset, nios2_gen2_0:reset_n, onchip_memory2_0:reset, rst_translator:in_reset, sdram_pll:reset, sysid_qsys_0:reset_n, tracker_status_pio:reset_n]
	wire         rst_controller_reset_out_reset_req;                          // rst_controller:reset_req -> [nios2_gen2_0:reset_req, onchip_memory2_0:reset_req, rst_translator:reset_req_in]
	wire         nios2_gen2_0_debug_reset_request_reset;                      // nios2_gen2_0:debug_reset_request -> [rst_controller:reset_in1, rst_controller_002:reset_in1]
	wire         rst_controller_001_reset_out_reset;                          // rst_controller_001:reset_out -> [jtag_uart_0:rst_n, mm_interconnect_0:jtag_uart_0_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_002_reset_out_reset;                          // rst_controller_002:reset_out -> [mm_interconnect_0:sdram_reset_reset_bridge_in_reset_reset, sdram:reset_n]

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (4),
		.FIFO_DEPTH_LOG2 (2)
	) audio_i2c_0 (
		.clk       (clk_clk),                                     //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),             //       reset_sink.reset_n
		.intr      (),                                            // interrupt_sender.irq
		.addr      (mm_interconnect_0_audio_i2c_0_csr_address),   //              csr.address
		.read      (mm_interconnect_0_audio_i2c_0_csr_read),      //                 .read
		.write     (mm_interconnect_0_audio_i2c_0_csr_write),     //                 .write
		.writedata (mm_interconnect_0_audio_i2c_0_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_audio_i2c_0_csr_readdata),  //                 .readdata
		.sda_in    (audio_i2c_0_i2c_serial_sda_in),               //       i2c_serial.sda_in
		.scl_in    (audio_i2c_0_i2c_serial_scl_in),               //                 .scl_in
		.sda_oe    (audio_i2c_0_i2c_serial_sda_oe),               //                 .sda_oe
		.scl_oe    (audio_i2c_0_i2c_serial_scl_oe),               //                 .scl_oe
		.src_data  (),                                            //      (terminated)
		.src_valid (),                                            //      (terminated)
		.src_ready (1'b0),                                        //      (terminated)
		.snk_data  (16'b0000000000000000),                        //      (terminated)
		.snk_valid (1'b0),                                        //      (terminated)
		.snk_ready ()                                             //      (terminated)
	);

	project_soc_cam_ctrl_pio cam_ctrl_pio (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_cam_ctrl_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_cam_ctrl_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_cam_ctrl_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_cam_ctrl_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_cam_ctrl_pio_s1_readdata),   //                    .readdata
		.out_port   (cam_ctrl_export)                               // external_connection.export
	);

	project_soc_effect_event_pio effect_event_pio (
		.clk        (clk_clk),                                          //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                  //               reset.reset_n
		.address    (mm_interconnect_0_effect_event_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_effect_event_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_effect_event_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_effect_event_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_effect_event_pio_s1_readdata),   //                    .readdata
		.out_port   (effect_event_pio_external_connection_export)       // external_connection.export
	);

	project_soc_frame_counter_pio frame_counter_pio (
		.clk      (clk_clk),                                         //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address  (mm_interconnect_0_frame_counter_pio_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_frame_counter_pio_s1_readdata), //                    .readdata
		.in_port  (frame_counter_pio_external_connection_export)     // external_connection.export
	);

	project_soc_effect_event_pio fruit0_desc_pio (
		.clk        (clk_clk),                                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address    (mm_interconnect_0_fruit0_desc_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_fruit0_desc_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_fruit0_desc_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_fruit0_desc_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_fruit0_desc_pio_s1_readdata),   //                    .readdata
		.out_port   (fruit0_desc_pio_external_connection_export)       // external_connection.export
	);

	project_soc_effect_event_pio fruit1_desc_pio (
		.clk        (clk_clk),                                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address    (mm_interconnect_0_fruit1_desc_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_fruit1_desc_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_fruit1_desc_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_fruit1_desc_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_fruit1_desc_pio_s1_readdata),   //                    .readdata
		.out_port   (fruit1_desc_pio_external_connection_export)       // external_connection.export
	);

	project_soc_effect_event_pio fruit2_desc_pio (
		.clk        (clk_clk),                                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address    (mm_interconnect_0_fruit2_desc_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_fruit2_desc_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_fruit2_desc_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_fruit2_desc_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_fruit2_desc_pio_s1_readdata),   //                    .readdata
		.out_port   (fruit2_desc_pio_external_connection_export)       // external_connection.export
	);

	project_soc_effect_event_pio fruit3_desc_pio (
		.clk        (clk_clk),                                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address    (mm_interconnect_0_fruit3_desc_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_fruit3_desc_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_fruit3_desc_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_fruit3_desc_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_fruit3_desc_pio_s1_readdata),   //                    .readdata
		.out_port   (fruit3_desc_pio_external_connection_export)       // external_connection.export
	);

	project_soc_effect_event_pio game_ctrl_pio (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_game_ctrl_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_game_ctrl_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_game_ctrl_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_game_ctrl_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_game_ctrl_pio_s1_readdata),   //                    .readdata
		.out_port   (game_ctrl_pio_external_connection_export)       // external_connection.export
	);

	altera_avalon_i2c #(
		.USE_AV_ST       (0),
		.FIFO_DEPTH      (8),
		.FIFO_DEPTH_LOG2 (3)
	) i2c_0 (
		.clk       (clk_clk),                               //            clock.clk
		.rst_n     (~rst_controller_reset_out_reset),       //       reset_sink.reset_n
		.intr      (),                                      // interrupt_sender.irq
		.addr      (mm_interconnect_0_i2c_0_csr_address),   //              csr.address
		.read      (mm_interconnect_0_i2c_0_csr_read),      //                 .read
		.write     (mm_interconnect_0_i2c_0_csr_write),     //                 .write
		.writedata (mm_interconnect_0_i2c_0_csr_writedata), //                 .writedata
		.readdata  (mm_interconnect_0_i2c_0_csr_readdata),  //                 .readdata
		.sda_in    (i2c_0_i2c_serial_sda_in),               //       i2c_serial.sda_in
		.scl_in    (i2c_0_i2c_serial_scl_in),               //                 .scl_in
		.sda_oe    (i2c_0_i2c_serial_sda_oe),               //                 .sda_oe
		.scl_oe    (i2c_0_i2c_serial_scl_oe),               //                 .scl_oe
		.src_data  (),                                      //      (terminated)
		.src_valid (),                                      //      (terminated)
		.src_ready (1'b0),                                  //      (terminated)
		.snk_data  (16'b0000000000000000),                  //      (terminated)
		.snk_valid (1'b0),                                  //      (terminated)
		.snk_ready ()                                       //      (terminated)
	);

	project_soc_jtag_uart_0 jtag_uart_0 (
		.clk            (clk_clk),                                                     //               clk.clk
		.rst_n          (~rst_controller_001_reset_out_reset),                         //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                     //               irq.irq
	);

	project_soc_keys_pio keys_pio (
		.clk      (clk_clk),                                //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_keys_pio_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_keys_pio_s1_readdata), //                    .readdata
		.in_port  (keys_export)                             // external_connection.export
	);

	project_soc_nios2_gen2_0 nios2_gen2_0 (
		.clk                                 (clk_clk),                                                    //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                            //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                         //                          .reset_req
		.d_address                           (nios2_gen2_0_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_gen2_0_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_gen2_0_data_master_read),                              //                          .read
		.d_readdata                          (nios2_gen2_0_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_gen2_0_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_gen2_0_data_master_write),                             //                          .write
		.d_writedata                         (nios2_gen2_0_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_gen2_0_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_gen2_0_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_gen2_0_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_gen2_0_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_gen2_0_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_gen2_0_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_gen2_0_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                            // custom_instruction_master.readra
	);

	project_soc_onchip_memory2_0 onchip_memory2_0 (
		.clk        (clk_clk),                                          //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                   // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),               //       .reset_req
		.freeze     (1'b0)                                              // (terminated)
	);

	project_soc_sdram sdram (
		.clk            (sdram_pll_c0_clk),                         //   clk.clk
		.reset_n        (~rst_controller_002_reset_out_reset),      // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	project_soc_sdram_pll sdram_pll (
		.clk                (clk_clk),                                         //       inclk_interface.clk
		.reset              (rst_controller_reset_out_reset),                  // inclk_interface_reset.reset
		.read               (mm_interconnect_0_sdram_pll_pll_slave_read),      //             pll_slave.read
		.write              (mm_interconnect_0_sdram_pll_pll_slave_write),     //                      .write
		.address            (mm_interconnect_0_sdram_pll_pll_slave_address),   //                      .address
		.readdata           (mm_interconnect_0_sdram_pll_pll_slave_readdata),  //                      .readdata
		.writedata          (mm_interconnect_0_sdram_pll_pll_slave_writedata), //                      .writedata
		.c0                 (sdram_pll_c0_clk),                                //                    c0.clk
		.c1                 (sdram_clk_clk),                                   //                    c1.clk
		.scandone           (),                                                //           (terminated)
		.scandataout        (),                                                //           (terminated)
		.areset             (1'b0),                                            //           (terminated)
		.locked             (),                                                //           (terminated)
		.phasedone          (),                                                //           (terminated)
		.phasecounterselect (4'b0000),                                         //           (terminated)
		.phaseupdown        (1'b0),                                            //           (terminated)
		.phasestep          (1'b0),                                            //           (terminated)
		.scanclk            (1'b0),                                            //           (terminated)
		.scanclkena         (1'b0),                                            //           (terminated)
		.scandata           (1'b0),                                            //           (terminated)
		.configupdate       (1'b0)                                             //           (terminated)
	);

	project_soc_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                       //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	project_soc_frame_counter_pio tracker_status_pio (
		.clk      (clk_clk),                                          //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                  //               reset.reset_n
		.address  (mm_interconnect_0_tracker_status_pio_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_tracker_status_pio_s1_readdata), //                    .readdata
		.in_port  (tracker_status_pio_external_connection_export)     // external_connection.export
	);

	project_soc_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                  (clk_clk),                                                     //                                clk_0_clk.clk
		.sdram_pll_c0_clk                               (sdram_pll_c0_clk),                                            //                             sdram_pll_c0.clk
		.jtag_uart_0_reset_reset_bridge_in_reset_reset  (rst_controller_001_reset_out_reset),                          //  jtag_uart_0_reset_reset_bridge_in_reset.reset
		.nios2_gen2_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                              // nios2_gen2_0_reset_reset_bridge_in_reset.reset
		.sdram_reset_reset_bridge_in_reset_reset        (rst_controller_002_reset_out_reset),                          //        sdram_reset_reset_bridge_in_reset.reset
		.nios2_gen2_0_data_master_address               (nios2_gen2_0_data_master_address),                            //                 nios2_gen2_0_data_master.address
		.nios2_gen2_0_data_master_waitrequest           (nios2_gen2_0_data_master_waitrequest),                        //                                         .waitrequest
		.nios2_gen2_0_data_master_byteenable            (nios2_gen2_0_data_master_byteenable),                         //                                         .byteenable
		.nios2_gen2_0_data_master_read                  (nios2_gen2_0_data_master_read),                               //                                         .read
		.nios2_gen2_0_data_master_readdata              (nios2_gen2_0_data_master_readdata),                           //                                         .readdata
		.nios2_gen2_0_data_master_write                 (nios2_gen2_0_data_master_write),                              //                                         .write
		.nios2_gen2_0_data_master_writedata             (nios2_gen2_0_data_master_writedata),                          //                                         .writedata
		.nios2_gen2_0_data_master_debugaccess           (nios2_gen2_0_data_master_debugaccess),                        //                                         .debugaccess
		.nios2_gen2_0_instruction_master_address        (nios2_gen2_0_instruction_master_address),                     //          nios2_gen2_0_instruction_master.address
		.nios2_gen2_0_instruction_master_waitrequest    (nios2_gen2_0_instruction_master_waitrequest),                 //                                         .waitrequest
		.nios2_gen2_0_instruction_master_read           (nios2_gen2_0_instruction_master_read),                        //                                         .read
		.nios2_gen2_0_instruction_master_readdata       (nios2_gen2_0_instruction_master_readdata),                    //                                         .readdata
		.audio_i2c_0_csr_address                        (mm_interconnect_0_audio_i2c_0_csr_address),                   //                          audio_i2c_0_csr.address
		.audio_i2c_0_csr_write                          (mm_interconnect_0_audio_i2c_0_csr_write),                     //                                         .write
		.audio_i2c_0_csr_read                           (mm_interconnect_0_audio_i2c_0_csr_read),                      //                                         .read
		.audio_i2c_0_csr_readdata                       (mm_interconnect_0_audio_i2c_0_csr_readdata),                  //                                         .readdata
		.audio_i2c_0_csr_writedata                      (mm_interconnect_0_audio_i2c_0_csr_writedata),                 //                                         .writedata
		.cam_ctrl_pio_s1_address                        (mm_interconnect_0_cam_ctrl_pio_s1_address),                   //                          cam_ctrl_pio_s1.address
		.cam_ctrl_pio_s1_write                          (mm_interconnect_0_cam_ctrl_pio_s1_write),                     //                                         .write
		.cam_ctrl_pio_s1_readdata                       (mm_interconnect_0_cam_ctrl_pio_s1_readdata),                  //                                         .readdata
		.cam_ctrl_pio_s1_writedata                      (mm_interconnect_0_cam_ctrl_pio_s1_writedata),                 //                                         .writedata
		.cam_ctrl_pio_s1_chipselect                     (mm_interconnect_0_cam_ctrl_pio_s1_chipselect),                //                                         .chipselect
		.effect_event_pio_s1_address                    (mm_interconnect_0_effect_event_pio_s1_address),               //                      effect_event_pio_s1.address
		.effect_event_pio_s1_write                      (mm_interconnect_0_effect_event_pio_s1_write),                 //                                         .write
		.effect_event_pio_s1_readdata                   (mm_interconnect_0_effect_event_pio_s1_readdata),              //                                         .readdata
		.effect_event_pio_s1_writedata                  (mm_interconnect_0_effect_event_pio_s1_writedata),             //                                         .writedata
		.effect_event_pio_s1_chipselect                 (mm_interconnect_0_effect_event_pio_s1_chipselect),            //                                         .chipselect
		.frame_counter_pio_s1_address                   (mm_interconnect_0_frame_counter_pio_s1_address),              //                     frame_counter_pio_s1.address
		.frame_counter_pio_s1_readdata                  (mm_interconnect_0_frame_counter_pio_s1_readdata),             //                                         .readdata
		.fruit0_desc_pio_s1_address                     (mm_interconnect_0_fruit0_desc_pio_s1_address),                //                       fruit0_desc_pio_s1.address
		.fruit0_desc_pio_s1_write                       (mm_interconnect_0_fruit0_desc_pio_s1_write),                  //                                         .write
		.fruit0_desc_pio_s1_readdata                    (mm_interconnect_0_fruit0_desc_pio_s1_readdata),               //                                         .readdata
		.fruit0_desc_pio_s1_writedata                   (mm_interconnect_0_fruit0_desc_pio_s1_writedata),              //                                         .writedata
		.fruit0_desc_pio_s1_chipselect                  (mm_interconnect_0_fruit0_desc_pio_s1_chipselect),             //                                         .chipselect
		.fruit1_desc_pio_s1_address                     (mm_interconnect_0_fruit1_desc_pio_s1_address),                //                       fruit1_desc_pio_s1.address
		.fruit1_desc_pio_s1_write                       (mm_interconnect_0_fruit1_desc_pio_s1_write),                  //                                         .write
		.fruit1_desc_pio_s1_readdata                    (mm_interconnect_0_fruit1_desc_pio_s1_readdata),               //                                         .readdata
		.fruit1_desc_pio_s1_writedata                   (mm_interconnect_0_fruit1_desc_pio_s1_writedata),              //                                         .writedata
		.fruit1_desc_pio_s1_chipselect                  (mm_interconnect_0_fruit1_desc_pio_s1_chipselect),             //                                         .chipselect
		.fruit2_desc_pio_s1_address                     (mm_interconnect_0_fruit2_desc_pio_s1_address),                //                       fruit2_desc_pio_s1.address
		.fruit2_desc_pio_s1_write                       (mm_interconnect_0_fruit2_desc_pio_s1_write),                  //                                         .write
		.fruit2_desc_pio_s1_readdata                    (mm_interconnect_0_fruit2_desc_pio_s1_readdata),               //                                         .readdata
		.fruit2_desc_pio_s1_writedata                   (mm_interconnect_0_fruit2_desc_pio_s1_writedata),              //                                         .writedata
		.fruit2_desc_pio_s1_chipselect                  (mm_interconnect_0_fruit2_desc_pio_s1_chipselect),             //                                         .chipselect
		.fruit3_desc_pio_s1_address                     (mm_interconnect_0_fruit3_desc_pio_s1_address),                //                       fruit3_desc_pio_s1.address
		.fruit3_desc_pio_s1_write                       (mm_interconnect_0_fruit3_desc_pio_s1_write),                  //                                         .write
		.fruit3_desc_pio_s1_readdata                    (mm_interconnect_0_fruit3_desc_pio_s1_readdata),               //                                         .readdata
		.fruit3_desc_pio_s1_writedata                   (mm_interconnect_0_fruit3_desc_pio_s1_writedata),              //                                         .writedata
		.fruit3_desc_pio_s1_chipselect                  (mm_interconnect_0_fruit3_desc_pio_s1_chipselect),             //                                         .chipselect
		.game_ctrl_pio_s1_address                       (mm_interconnect_0_game_ctrl_pio_s1_address),                  //                         game_ctrl_pio_s1.address
		.game_ctrl_pio_s1_write                         (mm_interconnect_0_game_ctrl_pio_s1_write),                    //                                         .write
		.game_ctrl_pio_s1_readdata                      (mm_interconnect_0_game_ctrl_pio_s1_readdata),                 //                                         .readdata
		.game_ctrl_pio_s1_writedata                     (mm_interconnect_0_game_ctrl_pio_s1_writedata),                //                                         .writedata
		.game_ctrl_pio_s1_chipselect                    (mm_interconnect_0_game_ctrl_pio_s1_chipselect),               //                                         .chipselect
		.i2c_0_csr_address                              (mm_interconnect_0_i2c_0_csr_address),                         //                                i2c_0_csr.address
		.i2c_0_csr_write                                (mm_interconnect_0_i2c_0_csr_write),                           //                                         .write
		.i2c_0_csr_read                                 (mm_interconnect_0_i2c_0_csr_read),                            //                                         .read
		.i2c_0_csr_readdata                             (mm_interconnect_0_i2c_0_csr_readdata),                        //                                         .readdata
		.i2c_0_csr_writedata                            (mm_interconnect_0_i2c_0_csr_writedata),                       //                                         .writedata
		.jtag_uart_0_avalon_jtag_slave_address          (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //            jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write            (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),       //                                         .write
		.jtag_uart_0_avalon_jtag_slave_read             (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),        //                                         .read
		.jtag_uart_0_avalon_jtag_slave_readdata         (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                                         .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata        (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                                         .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest      (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                                         .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect       (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  //                                         .chipselect
		.keys_pio_s1_address                            (mm_interconnect_0_keys_pio_s1_address),                       //                              keys_pio_s1.address
		.keys_pio_s1_readdata                           (mm_interconnect_0_keys_pio_s1_readdata),                      //                                         .readdata
		.nios2_gen2_0_debug_mem_slave_address           (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),      //             nios2_gen2_0_debug_mem_slave.address
		.nios2_gen2_0_debug_mem_slave_write             (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),        //                                         .write
		.nios2_gen2_0_debug_mem_slave_read              (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),         //                                         .read
		.nios2_gen2_0_debug_mem_slave_readdata          (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),     //                                         .readdata
		.nios2_gen2_0_debug_mem_slave_writedata         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),    //                                         .writedata
		.nios2_gen2_0_debug_mem_slave_byteenable        (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),   //                                         .byteenable
		.nios2_gen2_0_debug_mem_slave_waitrequest       (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest),  //                                         .waitrequest
		.nios2_gen2_0_debug_mem_slave_debugaccess       (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess),  //                                         .debugaccess
		.onchip_memory2_0_s1_address                    (mm_interconnect_0_onchip_memory2_0_s1_address),               //                      onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                      (mm_interconnect_0_onchip_memory2_0_s1_write),                 //                                         .write
		.onchip_memory2_0_s1_readdata                   (mm_interconnect_0_onchip_memory2_0_s1_readdata),              //                                         .readdata
		.onchip_memory2_0_s1_writedata                  (mm_interconnect_0_onchip_memory2_0_s1_writedata),             //                                         .writedata
		.onchip_memory2_0_s1_byteenable                 (mm_interconnect_0_onchip_memory2_0_s1_byteenable),            //                                         .byteenable
		.onchip_memory2_0_s1_chipselect                 (mm_interconnect_0_onchip_memory2_0_s1_chipselect),            //                                         .chipselect
		.onchip_memory2_0_s1_clken                      (mm_interconnect_0_onchip_memory2_0_s1_clken),                 //                                         .clken
		.sdram_s1_address                               (mm_interconnect_0_sdram_s1_address),                          //                                 sdram_s1.address
		.sdram_s1_write                                 (mm_interconnect_0_sdram_s1_write),                            //                                         .write
		.sdram_s1_read                                  (mm_interconnect_0_sdram_s1_read),                             //                                         .read
		.sdram_s1_readdata                              (mm_interconnect_0_sdram_s1_readdata),                         //                                         .readdata
		.sdram_s1_writedata                             (mm_interconnect_0_sdram_s1_writedata),                        //                                         .writedata
		.sdram_s1_byteenable                            (mm_interconnect_0_sdram_s1_byteenable),                       //                                         .byteenable
		.sdram_s1_readdatavalid                         (mm_interconnect_0_sdram_s1_readdatavalid),                    //                                         .readdatavalid
		.sdram_s1_waitrequest                           (mm_interconnect_0_sdram_s1_waitrequest),                      //                                         .waitrequest
		.sdram_s1_chipselect                            (mm_interconnect_0_sdram_s1_chipselect),                       //                                         .chipselect
		.sdram_pll_pll_slave_address                    (mm_interconnect_0_sdram_pll_pll_slave_address),               //                      sdram_pll_pll_slave.address
		.sdram_pll_pll_slave_write                      (mm_interconnect_0_sdram_pll_pll_slave_write),                 //                                         .write
		.sdram_pll_pll_slave_read                       (mm_interconnect_0_sdram_pll_pll_slave_read),                  //                                         .read
		.sdram_pll_pll_slave_readdata                   (mm_interconnect_0_sdram_pll_pll_slave_readdata),              //                                         .readdata
		.sdram_pll_pll_slave_writedata                  (mm_interconnect_0_sdram_pll_pll_slave_writedata),             //                                         .writedata
		.sysid_qsys_0_control_slave_address             (mm_interconnect_0_sysid_qsys_0_control_slave_address),        //               sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata            (mm_interconnect_0_sysid_qsys_0_control_slave_readdata),       //                                         .readdata
		.tracker_status_pio_s1_address                  (mm_interconnect_0_tracker_status_pio_s1_address),             //                    tracker_status_pio_s1.address
		.tracker_status_pio_s1_readdata                 (mm_interconnect_0_tracker_status_pio_s1_readdata)             //                                         .readdata
	);

	project_soc_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_gen2_0_irq_irq)            //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.reset_in1      (nios2_gen2_0_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),         // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),     //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.reset_in1      (nios2_gen2_0_debug_reset_request_reset), // reset_in1.reset
		.clk            (sdram_pll_c0_clk),                       //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset),     // reset_out.reset
		.reset_req      (),                                       // (terminated)
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
