`ifndef AUDIO_START_PARAMS_SVH
`define AUDIO_START_PARAMS_SVH

// Generated by tools/convert_audio_adpcm_to_mem.py.
`define AUDIO_START_SAMPLE_COUNT 12009
`define AUDIO_START_BYTE_COUNT 6005
`define AUDIO_START_ADDR_WIDTH 13

`endif
